name: mtc_xackaton
description: project for mts hackathon

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  share: ^2.0.4
  url_launcher: ^6.1.14
  get_it: ^7.6.4
  dropdown_textfield: ^1.0.8
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  gif: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true